Dnsaddr support
libp2p/cpp-libp2p pull request #105
Opened 2021-01-25 08:02 UTC by igor-egorov

cannot be merged by now

2021-02-09 08:45 UTC, kamilsa approved these changes

2021-02-09 09:21 UTC, igor-egorov commented on include/libp2p/peer/address_repository/inmem_address_repository.hpp
> +        std::enable_shared_from_this<InmemAddressRepository> {
You are right. It should have `public` modifier stated explicitly

2021-02-09 09:22 UTC, igor-egorov commented on src/network/cares/CMakeLists.txt
> +find_package(Threads)
True

2021-02-10 09:28 UTC, xDimon requested changes

2021-02-10 09:28 UTC, xDimon commented on src/network/cares/cares.cpp
> +    } catch (std::runtime_error &e) {
const-ref, please

2021-02-10 09:28 UTC, xDimon commented on src/network/cares/cares.cpp
> +    if (processError(status)) {
It's not clear from the code how it works. Suggest to check status explicitly before error processing.

2021-02-10 09:28 UTC, xDimon commented on include/libp2p/network/cares/cares.hpp
> +namespace libp2p::network::cares {
This name confuses me. Think about to rename it, i.e. to **c_ares**

2021-02-10 11:03 UTC, igor-egorov commented on src/network/cares/cares.cpp
> +      assert(initialized_.compare_exchange_strong(expected, false));
Works as expected. I've checked - an additional if for calling ares_init is not needed - it's already there.

2021-02-10 17:07 UTC, xDimon approved these changes
Good job!

2021-02-11 06:34 UTC, merged