Refactor read write some
libp2p/cpp-libp2p pull request #206
Opened 2023-02-02 14:10 UTC by turuslan

- Deduplicate `read`/`write` implementations with `readFull`/`writeFull` which use `readSome`/`writeSome`
- Fix yamux `writeSome` (`YamuxStream::writeSome` must call `YamuxedConnection::write`, because reader expects exactly `YamuxFrame.length` data bytes)

2023-02-03 02:57 UTC, xDimon requested changes

2023-02-03 02:57 UTC, xDimon commented on include/libp2p/basic/read_full.hpp
> +  inline void _readFull(const std::shared_ptr<basic::Reader> &reader,
_readFull is cinfusing. Actually it is just 'read' free function.

2023-02-03 02:57 UTC, xDimon commented on include/libp2p/basic/read_full.hpp
> +      throw std::logic_error{"libp2p::readFull 0 bytes requested"};
I think it's non-breaking case. I think it would be enough to insert boost assert here

2023-02-03 02:57 UTC, xDimon commented on include/libp2p/basic/read_full.hpp
> +    std::weak_ptr<basic::Reader> _reader = reader;
We can make this variable in lambda capture list.

2023-02-03 02:57 UTC, xDimon commented on include/libp2p/basic/read_full.hpp
> +        [=, cb{std::move(cb)}](outcome::result<size_t> _n) mutable {
fyi: underscore-beginning variable name violates our name convention

2023-02-03 02:57 UTC, xDimon commented on include/libp2p/basic/write_full.hpp
> +
Same as above

2023-02-13 04:04 UTC, xDimon approved these changes

2023-11-03 10:40 UTC, xDimon approved these changes

2023-11-09 06:48 UTC, igor-egorov approved these changes

2023-11-09 06:52 UTC, igor-egorov commented
Probably, we have to raise clang version for Ubuntu CI host. (Not mandatory for this PR)

2023-11-09 06:54 UTC, merged